# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Comptes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testsUnitairesUbuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-devel.txt ]; then pip install -r requirements-devel.txt; fi
    - name: Tests
      run: |
        pytest .
  testsUnitairesWindows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        IF EXIST "requirements.txt" ( pip install -r requirements.txt )
        IF EXIST "requirements-devel.txt" ( pip install -r requirements-devel.txt )
    - name: Tests
      run: |
        pytest .
  testsUnitairesMacOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-devel.txt ]; then pip install -r requirements-devel.txt; fi
    - name: Tests sur les modeles
      run: |
        pytest .
